### ISSUE TITLE
Not possible to install hierarchical_collapse

### ISSUE THREAD

**Issue by carlospgmat03** [ipython-contrib/IPython-notebook-extensions#140]
I am almost sure this is not the correct place to ask for help. However, I cannot find other. I want to have the functionality of hierarchical_collapse. However after fighting for several days I only have  vague idea of what should be done. Unfortunately I am also new in ipython. I have successfully loaded gist, acording to the console log in chrome, after following the instructions in  
https://github.com/ipython-contrib/IPython-notebook-extensions/wiki

I cloned the git@github.com:ipython-contrib/IPython-notebook-extensions.git repository, and copied the 
but, once I try to do something similar with hierarchical_collapse, it says there is nothing to download. Moreover, in the console, I get a very simple message:

Failed to load extension(s): ["nbextensions/testing/hierarchical_collapse/main.js"] 
Error: Script error for: nbextensions/testing/hierarchical_collapse/main.js http://requirejs.org/docs/errors.html#scripterror {requireType: "scripterror", requireModules: Array[1], originalError: Event, stack: (...), message: "Script error for: nbextensions/testing/hierarchica…http://requirejs.org/docs/errors.html#scripterror"}

although its there. 
A similar behaviour with a simpler extension, namely cellstate.js:

Failed to load extension(s): ["nbextensions/testing/cellstate.js"] 
Error: Script error for: nbextensions/testing/cellstate.js http://requirejs.org/docs/errors.html#scripterror {requireType: "scripterror", requireModules: Array[1], originalError: Event, stack: (...), message: "Script error for: nbextensions/testing/cellstate.j…http://requirejs.org/docs/errors.html#scripterror"}

If you cannot help me here, could you point me to a better place to seek help? Thanks!

**Comment by jat255** [comment]
I'm not sure if this will help anybody, but after checking out the 2.x branch, I was able to get the hierarchical_collapse extension working with a little tweaking.

First, in your .ipython profile directory (I am using [hyperspy](https://github.com/hyperspy/hyperspy), so my profile is in C:\Users\Josh\.ipython\profile_hyperspy\) make sure that you have a ./static/custom/custom.js file that loads the extension like the following:

    require(["base/js/events"], function (events) {
        $([IPython.events]).on("app_initialized.NotebookApp", function () {
            IPython.load_extensions('testing/hierarchical_collapse/main')
        });
     });

After doing this, it still wasn't working. Looking in the Chrome javascript console, I saw that there was an error saying that `./static/custom/testing/hierarchical_collapse/main.css` could not be found. For some reason, the extension looks for `main.css` in the profile directory rather than in the `nbextensions` directory. By creating that folder and copying `main.css` from the extension folder to the newly created directory, I was able to get it working (note, I also have the codefolding extension running in these pictures):

![unfolded](https://cloud.githubusercontent.com/assets/1278301/5722621/abc9c970-9b0b-11e4-9992-a161fb679e68.png)

![folded](https://cloud.githubusercontent.com/assets/1278301/5722622/ad942dae-9b0b-11e4-9423-05493cc8a44f.png)

**Comment by AlJohri** [comment]
I'm also unable to install this extension on Jupyter 4.x.

![](http://puu.sh/mUPqa/91ced9a60a.png)

**Comment by jcb91** [comment]
@AlJohri what steps did you follow to get to the console log you posted?
The installation process for extensions in general is fraught with complications, unfortunately. It seems from your console log that you've managed to get a few others working successfully, however, so that's hopeful. How did you install & enable (for example) the init_cell extension? Given that you've got the config_menu extension loading, I guess you've also got the config page loading ok? The hierarchical collapse extension currently doesn't have a yaml file to allow enabling it through the config page, but that might be a simpler route for you to try...
In related news, I've made a replacement of hierarchical collapse for my own use, as I wanted the functionality and found it unreliable. I've not published it yet, but if you'd like to try it, I could put it up somewhere.

**Comment by jcb91** [comment]
It also seems that an attempt has been made to load the extension in an unlikely location, `nbextensions/hierarchical_collapse.js`, which, if you're following the repository file structure, wouldn't be a likely place to find it. This leads me to guess that this load attempt was perhaps made from a `custom.js` file similarly to jat225's description above, but with an edited path?

**Comment by jcb91** [comment]
You can also now see my collapsible headings extension at #466.

**Comment by juhasch** [comment]
Extension replaced by collapsible_headings
