### ISSUE TITLE
Jupyter 3.x setup.py missing 

### ISSUE THREAD

**Issue by syriaaccountability** [ipython-contrib/IPython-notebook-extensions#324]
When I checkout branch 3.x the setup.py file is missing. Including some other files.  I am guessing this means the older version can only be manually installed?

**Comment by juhasch** [comment]
Because of the changes between the 3.x and new 4.x branches (the 3.x repository was split in several new repositories and a lot of names and locations changes) only 4.x is supported for the new simpler installation procedure.

So unfortunately yes, you will need to install things manually for 3.x or dig deep into the details and modify the 4.x installation script for 3.x.
