### ISSUE TITLE
python markdown renders only in new notebooks

### ISSUE THREAD

**Issue by jhconning** [ipython-contrib/IPython-notebook-extensions#326]
I can get the python markdown extension to work nicely on newly created notebooks but I cannot get the same markdown to render in previously created notebooks when I add the same python markdown.  

Is there perhaps some ipython variable I have to toggle on previously created notebooks to get it to work?  If this is the case could a word to that effect be added to the documentation?

I'm using Ipython 4.0.0.

**Comment by juhasch** [comment]
This is probably  because your notebooks are not trusted.
See the [Wiki](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Python-Markdown):
`Python code is only executed when the notebook is trusted. So if your original Python code is still shown in rendered markdown output, please make sure your notebook is trusted.`
To trust a notebook use the `File->Trust Notebook` menu.

**Comment by motleytech** [comment]
@juhasch 
It will be very useful to add this explanation on the UI frontend, like a notification or warning on untrusted notebooks, along with the steps to trust the notebook.

**Comment by jhconning** [comment]
Thank you, that was the problem.
I've taken the liberty to update the Wiki entry to add @juhasch 's line that  "To trust a notebook use the File->Trust Notebook menu." and also made it so that the reader can follow a link on the word [trusted] (https://ipython.org/ipython-doc/dev/notebook/security.html) to the official "Security in Ipython notebooks" page which also mentions how to make a group of notebooks trusted from the command line.

I like @motleytech 's suggestion to add a notification to untrusted notebooks if the python markdown extension is enabled.

**Comment by juhasch** [comment]
I thought about adding an indicator before. I opened PR #329 for this.
