### ISSUE TITLE
Incomplete nbextensions displayed for /nbextensions

### ISSUE THREAD

**Issue by achampion** [ipython-contrib/IPython-notebook-extensions#368]
/nbextensions only displays a subset of the extensions in ~/Library/jupyter/nbextensions folder
The jupyter console shows discovery of many more extensions but only shows the up to Codefolding and then abruptly stops.
Tried different browsers (Safari, Chrome, Chrome Canary) all with the same result.

The console showed an error reading limit-output.yaml (couldn't read "default: **OUTPUT MUTED**" - removing the '*' fixed this error but still not displaying anything beyond Codefolding.

**Comment by jcb91** [comment]
@achampion OK, sounds strange. Could you paste the full javascript console output? Whereabouts is/are the `*` you refer to? do you mean line 18 of `limit_output.yaml`? That should read
```yaml
  default: **OUTPUT MUTED**
```

**Comment by jcb91** [comment]
Apologies, I think I got confused about which console you were referring to. When you said
> The console showed an error reading limit-output.yaml (couldn't read "default: OUTPUT MUTED"
I though you meant the browser javascript console, but I realise now you must mean the jupyter notebook shell console, since the client-side javascript doesn't know anything about the existence of yaml files in the first place. I suppose this might be something to do with the python  `yaml` module version, if asterisks seem like a problem? You could try quoting the offending text to see if that helps, so that it reads
```yaml
  default: "**OUTPUT MUTED**"
```
But, this seems like a separate problem to your partly-filled config page. Javascript console output would be helpful for that.

**Comment by achampion** [comment]
Yes, sorry the jupyter shell console. Quoting does fix the problem reading that .yaml file. Here's the out put from the console (I've * the ones that show up in the /nbextensions page):

```
[I 09:13:35.201 NotebookApp] Found 4.x extension NbExtensions menu item
[I 09:13:35.205 NotebookApp] Found 4.x extension Printview
[I 09:13:35.208 NotebookApp] Found 4.x extension zenmode
*[I 09:13:35.213 NotebookApp] Found 3.x, 4.x extension AutoSaveTime
*[I 09:13:35.219 NotebookApp] Found 3.x, 4.x extension Autoscroll
*[I 09:13:35.221 NotebookApp] Found 4.x extension Chrome Clipboard
*[I 09:13:35.224 NotebookApp] Found 4.x extension Codefolding
[I 09:13:35.227 NotebookApp] Found 3.x, 4.x extension Comment/Uncomment Hotkey
[I 09:13:35.228 NotebookApp] Found 4.x extension datestamper
[I 09:13:35.230 NotebookApp] Found 4.x extension Drag and Drop
[I 09:13:35.232 NotebookApp] Found 4.x extension Equation Auto Numbering
[I 09:13:35.234 NotebookApp] Found 4.x extension ExecuteTime
[I 09:13:35.236 NotebookApp] Found 3.x extension Exercise
[I 09:13:35.238 NotebookApp] Found 3.x, 4.x extension Help panel
[I 09:13:35.239 NotebookApp] Found 3.x 4.x extension Hide input
[I 09:13:35.241 NotebookApp] Found 3.x 4.x extension Hide input all
[I 09:13:35.242 NotebookApp] Found 3.x, Jupyter (4.x) extension highlighter
*[I 09:13:35.243 NotebookApp] Found 3.x, Jupyter (4.x) extension (some) LaTeX environments for Jupyter
[I 09:13:35.247 NotebookApp] Found 4.x extension Limit Output
[I 09:13:35.248 NotebookApp] Found 4.x extension Navigation-Hotkeys
[I 09:13:35.250 NotebookApp] Found 4.x extension Python Markdown
[I 09:13:35.251 NotebookApp] Found 4.x extension Rubberband
[I 09:13:35.254 NotebookApp] Found 4.x extension Ruler
[I 09:13:35.256 NotebookApp] Found 4.x extension Runtools
[I 09:13:35.258 NotebookApp] Found 4.x extension Search-Replace
[I 09:13:35.259 NotebookApp] Found 4.x extension Skip-Traceback
[I 09:13:35.261 NotebookApp] Found 4.x extension Table of Content
[I 09:13:35.265 NotebookApp] Found 3.x 4.x extension Toggle all line numbers
```

Also the /nbextensions page seems to ignore the setting `"nbext_hide_incompat": true` in the notebook.json, and doesn't remember it if you select it on the page.

**Comment by jcb91** [comment]
OK, so this seems like mainly an issue with the client-side javascript code rather than the server-side python part of the config extension. The fact that you get the first 5 extensions in alphabetical order of name indicates that probably something goes wrong with the code which is supposed to be rendering the UI elements for either `Codefolding` (the last extension shown), or `Comment/Uncomment Hotkey` (the first extension missing). The

Could you let me know:
* any and all messages in the browser's javascript console. If you're not sure how to open this (apologies if it's completely obvious to you already), you can find [some instructions here](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers).

Finally, are you using the latest version of the repository? Since PR #292 should hopefully have made a single extension's failure to load non-fatal for following extensions, I'd be interested to know whether your version includes that commit. If you're ok using git (again, apologies if I'm coming across as patronising, I have no idea who knows way more than me on here), could you let me know the output of

```bash
git rev-parse HEAD
```

or otherwise, the method you used to install the repository, and the date on which you did that.

**Comment by jcb91** [comment]
Actually, I deduce from the fact that you've got the newer version of `usability/limit_output`, that you've almost certainly got a version of `config/main` incorporating #292.

**Comment by achampion** [comment]
The latest git commit is: `331438daf246429cdcb9a07e857dfd10c6ad7340 Merge pull request #363 from jfbercher/master`

The last few lines of the java console shows:
```
main.js:383 Found extension: Codefolding
main.js:476 Found ext param: codefolding_hotkey
main.js:520 Uncaught (in promise) ReferenceError: ext_name is not defined(…)build_page @ main.js:520
```

Which is interesting because that is in config/main.js trying to inform of a failure to load an extension :)
Changes to `extension.Name` and it now loads all the extensions and very surprisingly there are no extension load errors .

**Comment by jcb91** [comment]
Progress! I've found a stupid typo in `config/main.js`, which means that if any extension fails to render its UI elements, processing is just canned, instead of a nice error message being displayed - exactly what it was trying to prevent. To whit,
https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/nbextensions/config/main.js#L520 should read

```javascript
$('<p/>').text('error loading extension ' + extension.Name)
```

This is addressed in #370. Hopefully this should get most of the remaining extensions to load, but it still won't fix whatever prevented `Codefolding` / `Comment/Uncomment Hotkey` loading in the first place.

**Comment by jcb91** [comment]
Ah, you beat me to it!

**Comment by jcb91** [comment]
Ok, so there are no extensions listed as failing to load at all? Either in the javascript console, or on the page? That does seem strange, as getting to line 520 at all implies something failed to load correctly...

**Comment by achampion** [comment]
Indeed, it is very strange, but nothing seems to have failed to load, so not sure how it was getting down that code branch. It looks like both Codefolding and Comment/Uncomment extensions are loaded correctly. A mystery!

**Comment by jcb91** [comment]
okey doke, good plan.
Thanks for your time :)
