### ISSUE TITLE
Failed to load resource after codefolding_hotkey on nbextensions page

### ISSUE THREAD

**Issue by flipphillips** [ipython-contrib/IPython-notebook-extensions#371]
Trying to diagnose this now, but, after pulling latest revisions- when I load the `nbextensions` page, the page stops loading right after the Codefolding plug in, and the error log gives me the following. 

I'm not sure what those are, but guessing something to do with style.min.css. Not sure what `.map` files are.

```
[Warning] Unexpected CSS token: : (style.min.css, line 6885)
[Warning] Unexpected CSS token: : (style.min.css, line 6891)
[Warning] Unexpected CSS token: : (style.min.css, line 6897)
[Warning] Unexpected CSS token: : (style.min.css, line 6903)
[Warning] Unexpected CSS token: : (style.min.css, line 6909)
[Log] Found extension: – "(some) LaTeX environments for Jupyter" (main.js, line 383)
[Log] Found extension: – "AutoSaveTime" (main.js, line 383)
[Log] Found ext param: – "autosavetime_set_starting_interval" (main.js, line 476)
[Log] Found ext param: – "autosavetime_starting_interval" (main.js, line 476)
[Log] Found ext param: – "autosavetime_show_selector" (main.js, line 476)
[Log] Found extension: – "Autoscroll" (main.js, line 383)
[Log] Found ext param: – "autoscroll_set_on_load" (main.js, line 476)
[Log] Found ext param: – "autoscroll_starting_threshold" (main.js, line 476)
[Log] Found ext param: – "autoscroll_show_selector" (main.js, line 476)
[Log] Found ext param: – "autoscroll_show_button" (main.js, line 476)
[Log] Found extension: – "Chrome Clipboard" (main.js, line 383)
[Log] Found extension: – "Codefolding" (main.js, line 383)
[Log] Found ext param: – "codefolding_hotkey" (main.js, line 476)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (underscore-min.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.map, line 0)
```

**Comment by flipphillips** [comment]
Update here- if I drag `comment-uncomment` _and_ `codefolding` out of the `nbextensions/usability/` directory, then the rest load OK.

**Comment by jcb91** [comment]
This sounds like a duplicate of #368, which seems to be fixed by #370. What seems to be happening is that one of either comment-uncomment or codefolding, or some combination of the two, doesn't quite load correctly in the client-side javascript, and then the bug in `nbextensions/config/main.js` from #370 causes all subsequent page-loading code to be abandoned. Could you try the fix in #370 and report back?

**Comment by jcb91** [comment]
The failure to load `underscore-min.map` and `jquery.min.map` are unrelated, I think. As far as I can tell (see, e.g. [this explanation](http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/), they (min.map files) are maps from minified javascript back to the non-minified source. As such, they're useful when developing, and included in the full build (e.g. dev versions of jupyter) but are frequently left out of production packages (e.g. the jupyter version obtained through pip). When the javascript console is open, the browser will try to load the min.map files in order to provide better log messages/debugging for the dev consoles. But, they're not actually required for any functionality, which is all provided in the minified versions anyway.

The `style.min.css`, being a CSS issue is also unrelated, but I'm not sure what's causing it.

**Comment by flipphillips** [comment]
Sorry, yes, a duplicate. I _swear_ I looked... yet- I did not see :) 

Making that change in #370  does, in fact, allow the rest of the stuff to load. So that's a very good start. And thank you very much for the explanation - gotta keep learning new things every day.

I'll continue to poke around and see if I can determine why those two are being a pain.

**Comment by jcb91** [comment]
Haha no worries, it's not a very obvious diagnosis to make anyway, what with all the extra error messages flying around :)

**Comment by flipphillips** [comment]
Forgive me if I'm confused, but I just received a thoughtful and courteous response from a GitHub project maintainer instead of a "Be more diligent before wasting my valuable time, which is _much_ more valuable than anyone else's, especially _yours_, noob!" I might need to take a few minutes here and gather my composure.
