### ISSUE TITLE
Consider making the package pip-installable

### ISSUE THREAD

**Issue by cel4** [ipython-contrib/IPython-notebook-extensions#393]
The current way of installing is very unintuitive. The `setup.py`here is more a shell-script than a real setup.py. Moreover it has hidden dependencies on third party modules.

Is there any reason for not using `setuptools` and simply install a dummy package to fit everything in the python ecosystem?

**Comment by jcb91** [comment]
You're absolutely right, I noticed this the other day when looking at the
`pyyaml` dependency (which, I think, is the only one which isn't also a
dependency of the notebook proper). I thought about changing it, but so far
haven't got round to it. If you fancy giving it a go, by all means do :)

**Comment by jcb91** [comment]
Actually, also, one other thing to consider is a potential rename of the
repo to fit with jupyter (see #334, most extensions, after all, work with
any kernel type). If a have no idea how pip might handle such a renaming,
but it'd be with thinking about (maybe even start with the new name
directly?)

**Comment by jfbercher** [comment]
I was also thinking that installing from pip could be useful to users; I have an attempt in my repo. 

Could somebody test this that installs from my git repo, branch test_pip:

`pip install git+https://github.com/jfbercher/IPython-notebook-extensions@test_pip#egg=IPython-contrib-nbextensions --user`
This works in my configuration (debian linux + pure python) but i do not know about other configs (anaconda/windows/macos)... Please report if it works. 

Some details: I have written a setup.py which uses setuptools, install specified requrements and then calls the original setup.py (renamed as install.py)

**Comment by juhasch** [comment]
I did not make `setup.py` use setuptool, because it is not a real Python package.
Considering all the questions coming up, it looks like it would be a good idea to make it so.

**Comment by jfbercher** [comment]
The pip-install I described above works for a clean Windows/Anaconda 2.3 install. I just had to upgrade psutil (?).

**Comment by JanSchulz** [comment]
normal package and then put the current installer into something so that `python -c "import nbextensions; nbextensions.install()"` does the work?

**Comment by jfbercher** [comment]
I think that this what I attempted above with pip: the pip install fires setup.py which itself fires install.py. That seems to work (but is not the same package manager as conda). 

Since pip/setuptools also enable to deploy data_files in the user directory (.local/..  under Linux) it should be possible to copy nbextension/ directly from setup.py. It would still remain to update all paths as does @juhasch in the original setup.py

**Comment by JanSchulz** [comment]
```
Collecting PyYAML (from pyaml->IPython-contrib-nbextensions)
  Downloading PyYAML-3.11.tar.gz (248kB)
    100% |################################| 249kB 1.1MB/s
Requirement already satisfied (use --upgrade to upgrade): path.py in c:\portabel\miniconda\envs\dev_34\lib\site-packages (from pickleshare->ipython>=4->IPython-contrib-nbextensions)
Building wheels for collected packages: pyaml, PyYAML
  Running setup.py bdist_wheel for pyaml
  Stored in directory: C:\Users\jschulz\AppData\Local\pip\Cache\wheels\b6\7f\d5\2e78837e29363d9634b407813124643aad805535b69d956808
  Running setup.py bdist_wheel for PyYAML
  Stored in directory: C:\Users\jschulz\AppData\Local\pip\Cache\wheels\fa\db\f6\dee55793d344f1706dc4a5a693298f0115241d1085cc212364
Successfully built pyaml PyYAML
Installing collected packages: psutil, PyYAML, pyaml, IPython-contrib-nbextensions
  Running setup.py install for IPython-contrib-nbextensions
Successfully installed IPython-contrib-nbextensions PyYAML psutil pyaml
```

-> not sure if it works: C:\Users\jschulz\AppData\Roaming\jupyter\nbextensions\usability\toc was not updated (aka reverted the change from the other PR) and I also didn't see any output from `print("Running source install")`

**Comment by jfbercher** [comment]
That is strange... 
Indeed, it does not seem to really run the install part. Here is the output I have. I also had similar things on Windows yesterday. where I am sur install worked because there were nothing at the beginning.  You may perhaps try with the switch -v (verbose) to see if it gives more info)
 - - -
$ pip install git+https://github.com/jfbercher/IPython-notebook-extensions@test_pip#egg=IPython-contrib-nbextensions --user 
Downloading/unpacking IPython-contrib-nbextensions from git+https://github.com/jfbercher/IPython-notebook-extensions@test_pip
  Cloning https://github.com/jfbercher/IPython-notebook-extensions (to test_pip) to /tmp/pip-build-58ui_c_6/IPython-contrib-nbextensions
  Running setup.py (path:/tmp/pip-build-58ui_c_6/IPython-contrib-nbextensions/setup.py) egg_info for package IPython-contrib-nbextensions
    
    *********************************************************************************************************
    IPython-contrib-nbextensions - (C) 2013-2015, IPython-contrib Developers - All rights reserved.
    
    contains a collection of extensions that add functionality to the Jupyter notebook. These extensions are
    mostly written in Javascript and will be loaded locally in your Browser.
    
    The IPython-contrib repository https://github.com/ipython-contrib/IPython-notebook-extensions
    is maintained independently by a group of users and developers and not officially related to the
    IPython development team.
    
    The maturity of the provided extensions may vary, please create an issue if you encounter any problems.
    
    Released under Modified BSD License, read COPYING file for more details.
    *********************************************************************************************************
    
    /usr/lib/python3/dist-packages/setuptools/dist.py:294: UserWarning: The version specified ('master') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    
Requirement already satisfied (use --upgrade to upgrade): ipython>=4 in /usr/local/lib/python3.5/dist-packages (from IPython-contrib-nbextensions)
Requirement already satisfied (use --upgrade to upgrade): jupyter in /home/bercherj/.local/lib/python3.5/site-packages (from IPython-contrib-nbextensions)
Requirement already satisfied (use --upgrade to upgrade): psutil in /usr/lib/python3/dist-packages (from IPython-contrib-nbextensions)
Requirement already satisfied (use --upgrade to upgrade): pyaml in /home/bercherj/.local/lib/python3.5/site-packages (from IPython-contrib-nbextensions)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /home/bercherj/.local/lib/python3.5/site-packages (from pyaml->IPython-contrib-nbextensions)
Installing collected packages: IPython-contrib-nbextensions
  Running setup.py install for IPython-contrib-nbextensions
    Running source install
    Configuration files directory: /home/bercherj/.jupyter
    Extensions and templates path: /home/bercherj/.local/share/jupyter
    Install Python extensions to /home/bercherj/.local/share/jupyter/extensions
    Install templates to /home/bercherj/.local/share/jupyter/templates
    Install notebook extensions to /home/bercherj/.local/share/jupyter/nbextensions
    Configuring /home/bercherj/.jupyter/jupyter_nbconvert_config.json
    Configuring /home/bercherj/.jupyter/jupyter_nbconvert_config.py
    Configuring /home/bercherj/.jupyter/jupyter_notebook_config.json
    Configuring /home/bercherj/.jupyter/jupyter_notebook_config.py
    
    *********************************************************************************************************
    IPython-contrib-nbextensions - (C) 2013-2015, IPython-contrib Developers - All rights reserved.
    
    contains a collection of extensions that add functionality to the Jupyter notebook. These extensions are
    mostly written in Javascript and will be loaded locally in your Browser.
    
    The IPython-contrib repository https://github.com/ipython-contrib/IPython-notebook-extensions
    is maintained independently by a group of users and developers and not officially related to the
    IPython development team.
    
    The maturity of the provided extensions may vary, please create an issue if you encounter any problems.
    
    Released under Modified BSD License, read COPYING file for more details.
    *********************************************************************************************************
    
    /usr/lib/python3/dist-packages/setuptools/dist.py:294: UserWarning: The version specified ('master') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    
Successfully installed IPython-contrib-nbextensions
Cleaning up...

**Comment by jfbercher** [comment]
Arg. got it. I was using an old version of pip
 
    bercherj@pc-jfb-lenovo:~/.local/share$ pip --version
    pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.5)
    bercherj@pc-jfb-lenovo:~/.local/share$ pip3.5 --version
    pip 7.1.2 from /usr/local/lib/python3.5/site-packages (python 3.5)

It works with 1.5.6 but not with 7.1.2. Further investigations are needed..

**Comment by jfbercher** [comment]
Curiously, it still works from the archive version
pip3.5 install https://github.com/jfbercher/IPython-notebook-extensions/archive/test_pip.zip --user -v

**Comment by juhasch** [comment]
@jfbercher: would you make a PR for your pip-install ?
I think it would be great to make this work together with the new conda installation receipe #417

**Comment by juhasch** [comment]
Sure. I am currently not able to do much,too.
Another approach might be this:
https://github.com/jdfreder/jupyter-pip

**Comment by damianavila** [comment]
Related with this... https://github.com/ipython-contrib/IPython-notebook-extensions/issues/421#issuecomment-159751431

**Comment by juhasch** [comment]
Extensions now installable using Pip.
