### ISSUE TITLE
Gist it is missing the config.yaml file

### ISSUE THREAD

**Issue by bbirand** [ipython-contrib/IPython-notebook-extensions#412]
I didn't manage to install the `gist_it` extension via the `/nbextensions/` interface. I guess it's because it's missing the yaml file?

**Comment by jcb91** [comment]
Having no yaml descriptor, there's no way for the config interface at `/nbextensions` to know that the extension exists. However, the reason that there's no yaml file or readme is because the extension hasn't yet been updated to work with 4.x (which I can tell from the fact it doesn't use the `define` pattern)...

**Comment by jcb91** [comment]
(see also #204)

**Comment by jcb91** [comment]
I've had a stab at an updated version, which you can see in the branch `publishing/gist_it` at [jcb91/IPython-notebook-extensions](https://github.com/jcb91/IPython-notebook-extensions). For the moment, it only supports anonymous gists, which don't require authentication.

**Comment by jcb91** [comment]
now dealt with in PR #419
