### ISSUE TITLE
Uncaught Error: Mismatched anonymous define() in config extension

### ISSUE THREAD

**Issue by LunarLanding** [ipython-contrib/IPython-notebook-extensions#420]
Full error here:
https://gist.github.com/LunarLanding/fc7bd5668dd566121ab1
Replaced the "define" call in config/main.js by "require", got a different error:
![screen shot 2015-11-20 at 11 57 19](https://cloud.githubusercontent.com/assets/4441338/11299338/e07ec596-8f7d-11e5-8ff9-8f677e6e247f.png)

**Comment by jcb91** [comment]
Hi @LunarLanding, thanks for your report. I'm sorry to say that this is probably my fault!
The error you get when switching to use `require` is a a result of a call to `require.toUrl` with a relative path (`./main.css`) in the `config/main.js` module, which only works when it's inside a `define` (since the define is what allows the resolution of relative URLs). Without the define, it looks like this ends up looking for the css at `static/main.css` instead of `nbextensions/config/main.css`.

As for the `Mismatched anonymous define`, I'm not sure yet, I'll have a think. What browser/OS combo(s) are you using?

**Comment by LunarLanding** [comment]
I'm using Chrome, in OSX. I'll try to reproduce in winpython,  Windows 10
and chrome, fresh install using setup.py.

**Comment by jcb91** [comment]
oh dear, I'm using exactly the same :(

**Comment by LunarLanding** [comment]
Here's the page source, where the error-ing javascript is beong loaded : https://gist.github.com/LunarLanding/3d63bcd6c8300803b9b5

**Comment by jcb91** [comment]
Aha! Hints. So, at https://gist.github.com/LunarLanding/3d63bcd6c8300803b9b5#file-nbextensions-L139, we see a script tag with a `src` attribute:

```HTML
<script src="/nbextensions/config/main.js" type="text/javascript" charset="utf-8"></script>
```

This should instead be a script tag using the requirejs API, as follows:

```HTML
<script type="text/javascript" charset="utf-8">
		require(["nbextensions/config/main"]);
</script>
```

This should have already been changed in 69565b22de4be8d00067ee72da50694e9551f4f7, I think? What version of the repo are you using?

**Comment by LunarLanding** [comment]
I can confirm that I have the up to date template and main.js in the nbextensions folder. I'm now looking for the old template, it must be somewhere on my system being picked up first.

**Comment by LunarLanding** [comment]
Ok, somehow I still had an .ipython folder. I deleted it, and reinstalled jupyter. It's working now!
