### ISSUE TITLE
ToC currently unusable in Chrome

### ISSUE THREAD

**Issue by JanSchulz** [ipython-contrib/IPython-notebook-extensions#424]
See here: https://github.com/jupyter/notebook/issues/699

Using this bugreport to see if we can add any workaround or need to change something if the notebook changes something...

**Comment by jfbercher** [comment]
Hi Jan,

Thanks for the input. I have also noted some scrolling issues that are a
bit annoying. But for me the toc is not unusable (perhaps because I use
chromum, not chrome?). I hope a correct solution can be found.
It should be still possible here, in the toc extension itself, to override
the texcell prototype with the patch proposed in #699, so that the users do
not have to do it themselves.
For my part, I have updated the toc extension with some new features, but
unfortunately I am super busy and I do have time to properly upload it to
IPython-contrib (perhaps this we). If you want to have a look, it is here:
https://raw.githubusercontent.com/jfbercher/small_nbextensions/master/toc2.zip

Jean-François
http://www.esiee.fr/~bercherj

**Comment by JanSchulz** [comment]
As far as I understand the workaround, the onclick unrender-render step for the textcell is needed. So IMO, if we want to do the workaround here, we need to get an handle to the textcell in the link to the headline. Not sure if that's possible as we currently do a simple search for a headline (which is in the rendered textcell). Not sure if there is some way to get from the headline to the textcell object, at least not for my very basic js skills :-/

**Comment by JanSchulz** [comment]
This is actually fixed, at least in toc2 code -> I currently use it and it works like a charm.
