### ISSUE TITLE
Possible bug in ExecuteTime extension

### ISSUE THREAD

**Issue by enascimento** [ipython-contrib/IPython-notebook-extensions#436]
When running a cell several times, I get output like:
"Lastly executed on Fri, Dec 18 2015 at 9:18 PM in 3 min 13 s in 3 min 13 s in 3 min 20 s in 3 min 21 s"

There is a repetition of the elapsed time in the end of the line.

**Comment by jcb91** [comment]
Does this happen on every cell, every notebook? Even after reloading? Does aborting kernel executions affect things? Could you post the output of the [browser JavaScript console] (http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers)?

I'm not sure exactly why this is happening without more information, but i can suggest a couple of possibilities.

The first would be that the extension is somehow getting loaded multiple times, which causes each cell to register its execution call multiple times. This is fixed in the latest master jupyter, so extensions should only be loaded once each, but I don't recall which version fixed it. A quick check of the javascript console should show whether you have multiple "loaded extension ExecuteTime" messages. 

The second: as far as I can make out, the extension maintains a list of cells which have been executed, then pops them out in fifo order when a kernel idle notifications are fired. I don't think the list gets cleared if the kernel is told to abort evaluation, which, if there are multiple cells in the queue, might mean that they don't all get popped from the list, so when a subsequent execution happens, they may get extra times...

**Comment by jcb91** [comment]
presumably now closed by #470
