### ISSUE TITLE
Python 3.x dependency

### ISSUE THREAD

**Issue by kyrre** [ipython-contrib/IPython-notebook-extensions#454]
Is Python 3.x really a necessary dependency? There is an explicit version check in setup.py but it works on Python 2.7 if you comment it out.

**Comment by edvald** [comment]
Yeah I just came across this too. I've backtracked to an older version until this is fixed, or at least explained...

**Comment by jfbercher** [comment]
Indeed, Python 3 is not needed for installing (using setup.py). 

However, there some auxilliary utils, e.g.  conversion functions in some extensions packages that still require python 3 (or at least have been written with Py3 in mind). You are welcome to check this, and perhaps propose a PR which may update the dependancy  in setup.py, but provide a clear Warning to the users. 

You may also consider upgrading to py3... :-)

**Comment by vmuriart** [comment]
@edvald to which version did you backtrack to?

**Comment by edvald** [comment]
Sorry about the (very) late response. I had just checked out the commit hash previous to the setup.py change. But now I see that its been changed to show a warning instead of an error, so that works nicely!

I wish I could just switch to Py3 but, as is often the case, there's a whole lot of incompatible code that I need to deal with first... Hopefully I'll get there soon :) 

And thanks for all the work on this project, it's been very useful!

**Comment by juhasch** [comment]
Thanks for the feedback.
