### ISSUE TITLE
 `testing/hierarchical_collapse` deletes all cells while loading/saving the notebook

### ISSUE THREAD

**Issue by kkumer** [ipython-contrib/IPython-notebook-extensions#473]
This doesn't happen with all my notebooks, but when it happens it is completely reproducible.
I load the notebook and two things happen:

1. Cells fail to execute (nothing happens when either calling for execution via menu Cells-->Run Cells, or via keyboard shortcut)
2. Hitting "Save and Checkpoint" and then "Close and Halt" results in notebook file on disk with no cells! (I was lucky to have backup). 

I disable the extension and everything works fine. Enabling it, same problem again. This is Jupyter/IPython ver. 4.1.1.  I hope somebody fixes this badly needed extension.

**Comment by jcb91** [comment]
This sounds very strange. As an replacement, you could try the new [collapsible headings](https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/collapsible_headings) extension I wrote as my own replacement for `hierarchical_collapse`, as I found the latter to be buggy and an over-complicated implementation.

I didn't write any of the nbconvert templating stuff into my `collapsible_headings`, as I don't use it, but if you'd like it added, you could explore that.

If you'd like to get `hierarchical_collapse` fixed, these things would be helpful
1. Post any [javascript console](http://webmasters.stackexchange.com/questions/8525) output
2. Check the behaviour with hierarchical_collapse disabled, and with everything but hierarchical collapse disabled, to be sure we've caught the right bug(s).
3. Post a link to a copy of a notebook which shows this behaviour (if you've got confidential info in the one(s) you're currently using, any information about what they have in common, or an attempt to make a dummy one which triggers the problem behaviour).

Best, J

**Comment by kkumer** [comment]
Hey, great effort! Your collapsable_headings are working here (also with that problematic notebook). Small things: (1) I don't have that fa-plus/fa-minus icons to the left of heading cells. (2) Collapsed state is not persistent (after closing browser window and reopening, or after saving and reloading, all headings are open).  
But I can live with that..

**Comment by jcb91** [comment]
Ok, glad that helps. When you say you don't have the plus/minus icons, do you mean you still get the button, but it's blank? I wonder if your version skips unused fa icons? Im not sure. Anyway, you could try editing the `nbextensions/usability/collapsible_headings/main.js` file, replacing the classes with others, e.g. swap from [`fa-plus-circle`](http://fortawesome.github.io/Font-Awesome/icon/plus-circle/) to [`fa-plus-square`](http://fortawesome.github.io/Font-Awesome/icon/plus-square/) or just [`fa-plus`](http://fortawesome.github.io/Font-Awesome/icon/plus/), or perhaps instead of plus/minus, you could use [`fa-expand`](http://fortawesome.github.io/Font-Awesome/icon/expand/) and [`fa-compress`](http://fortawesome.github.io/Font-Awesome/icon/compress/), or [`fa-caret-right`](http://fortawesome.github.io/Font-Awesome/icon/caret-right/) and [`fa-caret-down`](http://fortawesome.github.io/Font-Awesome/icon/caret-down/) or [`caret-square-o-down`](https://fortawesome.github.io/Font-Awesome/icon/caret-square-o-down) and [`caret-square-o-up`](https://fortawesome.github.io/Font-Awesome/icon/caret-square-o-up). Just some ideas.

As for collapsed state not being persistent, that sounds like a bug. If you could post some javascript console output, it might help to clear that up.

**Comment by jcb91** [comment]
@kkumer, I've made a few updates on my branch of `collapsible_headings` (see #475) which might alter things. If you still have problems with icons (the classes, button-edging and color of which are now configurable on the `http://localhost:8888/nbextensions` config page), or with collapsed-state persistence, please let me know. One thing that did occur to me, is that although collapsing a heading sets a cell metadata value, it doesn't mark the notebook as 'dirty', so if you immediately reload the page without saving the notebook, the metadata may not get written to disk. Just a thought.

**Comment by kkumer** [comment]
`collapsible_headings` solves all the need for collapsing, making `hierarchical_collapse` extension largely obsolete, so I don't see the need to keep this issue open.
