### ISSUE TITLE
Collapsible Headings - buttons

### ISSUE THREAD

**Issue by OndrejMarsalek** [ipython-contrib/IPython-notebook-extensions#474]
Would it be possible to have a setting for the buttons on the left hand side that toggle section collapse? They are quite large and people who prefer to stay on the keyboard as much as possible likely don't use them anyway - the keyboard shortcuts are great.

**Comment by jcb91** [comment]
Absolutely, I'll get onto it.

**Comment by jcb91** [comment]
Right, I think it's done, see #475.

I found the buttons handy for gauging the level of each heading. I thought it might get confusing trying to tell whether sections were collapsed, or just empty without them, but it is a matter of opinion, I suppose. I've left the options to default to showing the buttons, anyway.

I've also slightly altered the functioning so that the `collapsible_heading_collapsed` css class is applied to the cell rather than the toggle button, so one could add custom css to show collapsed headings if that were helpful/preferable.

Hope that helps,
J

**Comment by jcb91** [comment]
(some more updates added to #475, more things are now configurable)
