### ISSUE TITLE
Persistence of collapsed state with collapsible_headings

### ISSUE THREAD

**Issue by kkumer** [ipython-contrib/IPython-notebook-extensions#482]
(This follows the discussion in #473 - it doesn't make sense to hijack another extension's issue.)

Sorry  for the delayed answer but I was quite busy. And during that I actually used collapsible_headings a lot and it's working great for me. So, what we are discussing here are just minor things. It turns out that my two problems: (1) Icons left of headings not shown (but I can collapse by clicking the right place) and (2) collapsed state not persistent over reloading the notebook (BTW, I was careful to save first) are happening only on my home computer (Chrome on Windows 10)  accessing remote jupyter server. When working localy at jupyter server machine (Chromium on Linux), everything is perfect. Icons are there and things are persistent.

Your new updates didn't help with persistence (when working from home), and helped partially with icons. Now only some are missing, some of the time. Note that  I can actually always bring icons into existence by executing the heading cell.
(BTW, I like the new triangle icons much better than those huge plusses.)

Here are javascript console errors:

`Font from origin 'null' has been blocked from loading by Cross-Origin Resource Sharing policy: Invalid response. Origin 'https://[MY SERVER HOSTNAME]:8888' is therefore not allowed access.`

`chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2 Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://[MY SERVER HOSTNAME]:8888" from accessing a frame with origin "chrome-extension://oknpjjbmpnndlpmnhmekjpocelpnlfdi".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "chrome-extension". Protocols must match.`

**Comment by jcb91** [comment]
OK, that's... confusing. Glad to hear it's sort of working, but I'm so far a bit stumped by the remote/local difference. So, just to ensure I've understood correctly, when you're working from the home machine, you're opening a browser on the home machine, and just entering the server hostname instead of the more common `localhost` right? So if that's the case, the server-side of the local and remote setups is exactly the same. 

The `Font from origin 'null' has been blocked from loading by Cross-Origin Resource Sharing` error is something I see in my console all the time, and it seems to be a normal part of MathJax loading (i.e. not actually an error, see https://github.com/mathjax/MathJax/issues/926#issuecomment-127452031).

The second one seems to be related to the StayFocusd chrome extension, which I'm not familiar with. It seems to suggest your notebook is inside an iframe - is that something you've arranged? It could equally be something that the extension does, although quite why the notebook frame should be reaching outside of itself I can't immediately guess. Could you try disabling the extension, see if that changes anything?

When you say of the icons "Now only some are missing, some of the time", is it always the same ones which are missing/present? Does the collapsing still work for the missing icons if you click where they ought to be?

The fact that persistence doesn't work, and only some icons display, suggests to me that the extension is running into an error somewhere in its initialisation, which means it doesn't get completed. Sometimes I've noticed some jquery-wrapped stuff can throw errors which don't make it out to the console. You could try adding a few `console.log(mod_name + 'line 210');` type calls in the main.js file to check how far it gets through the function - say after lines 459, 462, and maybe some calls at the entry and exit of the `update_heading_cell_status` function.

**Comment by kkumer** [comment]
You understood correctly: There is a single jupyter installation on linux server, and problems sometimes occur when connecting to it remotely by entering server's hostname into windows browser at home. Now, I have disabled all chrome/chromium extensions and all jupyter extension apart from collapsible_headings. It turns out that about 50% of my notebooks work flawlessly everywhere (collapsed state is persistent and icons are there), but 50% have this non-persistence problem on windows client (and some of the icons are missing, always the same I think but am not sure, and I can still collapse the section if I click at the right place).

Nonpersistence is present regardless of whether I collapsed these sections on server or on client. In both cases, after saving and then reloading on client all sections will be un-collapsed. (Also,  upon saving, I notice that `"heading_collapsed" : true` is deleted from notebook cells' metadata.)

I have added additional logging in main.js, as you proposed. On [this URL](http://calculon.phy.hr/pub/collapse.tgz) you can download logs of two notebooks being loaded in linux, and same two being loaded in windows, and you will find notebooks themselves. There are additional two logs of another two notebooks. Log filename starts with "good" or "bad" signifying whether notebook is behaving persistently or not. After cursory look, I notice two features of "bad" logs. First is that there are `expanded cell` log entries there, but this is probably trivially expected. Another is that lines "after 459, 462", which are lines 460 and 464 in modified main.js, are reached immediatelly, **before** all the calls to `update_heading_cell_status`, while in "good" logs, these lines are reached at the end of the loading process. I hope this is somehow significant.

**Comment by jcb91** [comment]
Great, thanks for the feedback! So, it seems from what you describe that somehow the initial loading on the windows client is expanding all of the headings, (which would delete the collapsed entries from the metadata, that's expected). As you note, the fact that the 460/464 lines come before the big spew of update_heading_cell_status calls is suggestive, since that 460 line should be after [main.js#L459](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/b508b0ffbda62ac935088f57b579bc9122743e88/nbextensions/usability/collapsible_headings/main.js#L459), which calls `update_heading_cell_status` for each cell. The fact that it happens on some notebooks and not on others makes me wonder if there isn't some racing going on somewhere, but I think for now it's probably best to just concentrate on diagnosis. Could you try replacing the line

```javascript
Jupyter.notebook.get_cells().forEach(update_heading_cell_status);
```

with an explicit for-loop of the form

```javascript
var cells = Jupyter.notebook.get_cells();
for (var ii=0; ii<cells.length; ii++) {
    update_heading_cell_status(cells[ii]);
}
```

Then, open developer console (ctrl-shift-J to open in Windows), select the 'sources' tab, and select the 'Pause on exceptions' control (the blue one in [this image](http://i.stack.imgur.com/CohjO.png)), before opening/refreshing the notebook page. That way you should (hopefully) catch what's going on. Good luck!

**Comment by kkumer** [comment]
I haven't yet played with sources in console, but after entering your explicit for loop I noticed that in "bad" case, `Jupyter.notebook.get_cells()` returns zero cells. You can see that from two attached console logs, which are obtained after I entered additional
```javascript
var cells = Jupyter.notebook.get_cells();
console.log(mod_name + ' TMP <location> # of cells = ' + cells.length);
```
on many places in the `main.js`. As far as I can see, problem is that upon loading your extension first thinks that notebook has zero cells, and then it receives `create.Cell` events for every single cell and recreates notebook in its default, uncollapsed state. Some race condition maybe?
Also, I have confirmed that problems is not due to WIndows, but due to remote connection. I have a problem also connecting with Linux machine. (And virtual Windows on the server are fine. This is a bit confusing since this should be treated as remote connection. Maybe the network latency is relevant?). It is also irrelevant whether I use Chrome or FIrefox.

FInally, I have some more insight into missing icons problem. Opening notebook on remote Chrome (on a "new" computer) there were no icons at all. To create icons I had to execute heading cells. Unless I did that, I couldn't collapse the section (I was wrong about that before, when I wrote that only icon is missing, and button is there, sorry for confusion.) But these icons are then persistent and are there after reload. They also persist if I close the notebook and open it in a different browser on the same computer  (going from Chrome to Firefox or back).

[bad-nb01-morelogs.log.txt](https://github.com/ipython-contrib/IPython-notebook-extensions/files/145614/bad-nb01-morelogs.log.txt)

[good-nb01-morelogs.log.txt](https://github.com/ipython-contrib/IPython-notebook-extensions/files/145615/good-nb01-morelogs.log.txt)

**Comment by jcb91** [comment]
Aha! I was thinking about this, and had come to the conclusion that in the normal load sequence I see, there shouldn't be any `expanded cell` or `collapsed cell` console logs on load, and that they'd only come from `create.Cell` callbacks. So, that, in addition to the fact that it seems to be an issue with remote machines of all types, and not so much with local ones, makes it sound like the issue is to do with when the notebook load happens relative to when the extension loads. This is my current hypothesis: If you're local, you have low latency and fast load times for the notebook, so the initial `create.Cell` events occur before the extension loads. If you're connecting to a server on a remote machine, the longer load time can mean that the extension loads before the notebook, then it catches all the `create.Cell` events which get fired as the initial notebook content is loaded once it arrives from the server. So it seems the triggers are a combination of network latency, notebook size, and other network timing bits and pieces. The icons problem is probably related, I think, essentially the updating of heading cells which should create the toggle controls isn't doing it, for a reason I've yet to determine. Perhaps it's something to do with when metadata is loaded, I'll have a look at the Jupyter source. I had seen something like this a couple of times in my own testing, but it was so rare, and quite some time ago, that I sort of assumed it had been cleaned up at some point and didn't look further, but clearly I was being insufficiently cautious! I'll try to wrap my head around this today or tomorrow.

**Comment by jcb91** [comment]
Right, so on closer inspection, what I think is going on is:

1. 
  * If the notebook loads quickly enough (local server, caching of images etc, all potentially relevant), all the `create.Cell` events before `notebook_loaded.Notebook` are over before the extension loads. Nothing happens.
  * If loading is slow, then the extension's `create.Cell` handler is registered, and each cell being created calls `reveal_cell_by_index` in the callback.
  * The intention behind this was to avoid a situation where one might create a cell below a heading, but then have it hidden by the collapsed heading. This was a little misguided, and, thinking about it again, unnecessary, since the newly created cell would be selected, which also gets `reveal_cell_by_index` called, so I can just remove the reveal call from the create callback.
2. In a similar timing issue, the ordering of a cell's data being loaded by its `fromJSON` function, and the `create.Cell` callback executing, is not well-defined. In general, it seems to be ok for me, and the callback executes only after the cell data has been loaded, so heading cells are recognised as such and have their toggles rendered. It seems like in your case, the callback executes _before_ the cell's text has been set, so the cell looks empty, and isn't recognised as a heading, so no toggle is rendered. This can be fixed by something I was planning to do anyway, which was to bind to the `rendered.MarkdownCell` event to determine heading status.

I'll knock something together, but I've already made a bunch of updates, so I'll probably just piggyback it onto those. Anyway, I'll post back once it's done

**Comment by jcb91** [comment]
I've made a fix in my branch, if you'd like to try that. Or, if you'd like to try a quick in-place edit first, I think it should be sufficient to:

 * replace the `create.Cell` callback at [nbextensions/usability/collapsible_headings/main.js#L452-L457](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/991ae98250d68c70a473478502c5467c98e63eb4/nbextensions/usability/collapsible_headings/main.js#L452-L457) with
```javascript
events.on('rendered.MarkdownCell', function (evt, data) {
	update_heading_cell_status(data.cell);
	update_collapsed_headings(data.cell);
});
```
* add another callback registration of the form
```javascript
events.on('notebook_loaded.Notebook', function (evt, data) {
	Jupyter.notebook.get_cells().forEach(update_heading_cell_status);
	update_collapsed_headings();
});
```

**Comment by kkumer** [comment]
O.K. just making above replacement/additions resulted in some hard error in console and notebook refused to load (and content was deleted in the process). But don't worry, I may have screwed up something. Anyway, I cloned your branch and used that and as far as I can see it works perfectly: my two problematic notebooks are now fine, icons are there, and collapsed state is persistent. So, I would say you solved it.  It was just a fast check and I will check it a bit more on Monday, but I think you can push it to main branch and issue can be closed.

**Comment by jcb91** [comment]
@kkumer, did #506 fix this for you, in the end?

**Comment by kkumer** [comment]
Indeed it has. I haven't done any special testing, but I have been using this heavily in production and it works without a glitch. Thanks a lot for this extension, I often have huge notebooks and it was frustrating before to scroll so much up and down.
