### ISSUE TITLE
Selecting heading cell and all children

### ISSUE THREAD

**Issue by Kevin-McIsaac** [ipython-contrib/IPython-notebook-extensions#485]
Now that notebooks support copy and past of a set of cells, it would be very useful to be able to select the heading cell and all its children with a single command. This would then the heading and all its children to be easily move. Indeed, I suspect this is more common that wanting to select just the heading. 

A few options:
1. Change the default so that selecting a heading select all the heading and all children.
2. Make shift-select of a heading select all children.
3. Single click of a heading bracket, anywhere, selects the heading and all children.

**Comment by jcb91** [comment]
Yep, seems like a good plan. As for options:

1. I think making it default might be a bit confusing/frustrating. But it would, I think, make sense to do this for _collapsed_ headings, as it seems a little more intuitive. This can be done probably quite easily, but it will mean that having a heading as the current cell will also highlight it as part of a multi-selection. I think I'd prefer new bindings
2. Shift-select is already bound, extending selection, so I don't think we ought to repurpose it. Maybe shift-left and shift right could be added as extra key bindings, to select/unselect all cells in the section?
3. Yep, brackets are an easy, intuitive option, so I can add that in addition to anything else

Thoughts?

**Comment by kkumer** [comment]
Also, note that in Mathematica if you select all cells via bracket, shift-Enter will execute all those cells. This is quite useful - I always have some sort of initialization section in my notebooks.

**Comment by jcb91** [comment]
@kkumer yep, once all the cells are selected, the usual ctrl-enter shortcut will queue all of them for execution.

**Comment by jcb91** [comment]
So, a preliminary solution is available at my branch https://github.com/jcb91/IPython-notebook-extensions/compare/master...usability/collapsible-headings. So far, this includes work to:

1. Add an extra keyboard shortcut (default shift-right) to select the heading's whole section.
2. Make the Mathematica-style brackets single-clickable to select the whole section
3. Decide whether selecting a whole section also reveals it (which was the default, and a bit annoying, so I made it configurable)
4. fixes an off-by-1 bug in `reveal_cell_by_index`
5. fixes the right-alignment of the Mathematica brackets, which I'd accidentally broken somewhere along the line
6. fixes toggle icon margins inside buttons, which I'd broken (insufficient testing, again, d'oh!)

As always, any thoughts welcome.

**Comment by jcb91** [comment]
So, a few more commits pushed to my branch, which should (hopefully):

 * Fix persistence and icon-showing issues seen by @kkumer in #482
 * Fix the config page setting mentioned by @Kevin-McIsaac in jcb91/IPython-notebook-extensions#1
 * Add a hover state, suggested by @Kevin-McIsaac, so brackets darken when hovered over
 * Make the bracket width configurable
 * Slightly alter bracket appearance, giving mitred corners (at least in Chrome, FF & Safari)

Just wondering, would it be worth making toggling a heading set the notebook as dirty (so that it will look unsaved, given metadata has changed)? I haven't bothered as yet, but it's not difficult, so I suppose it might as well be less surprising by not being autosaved, etc...

**Comment by jcb91** [comment]
Should now be fixed by #506
