### ISSUE TITLE
How can I uninstall all extensions?

### ISSUE THREAD

**Issue by cqcn1991** [ipython-contrib/IPython-notebook-extensions#505]
So I was experimenting with nbextension, and somehow, I don't remember what I've done, I just have an error in my browsers console

`Failed to load extension: ["nbextensions/usability/my_toc/toc_test"] `(One of my test files)

The problem is that I already delete that dir and diabled the extention. I tried to delete the `nbextension` dir and re-installed the `anaconda`. But the error is still there.

So I'm thinking, what's the correct way to erasing all nbextention files?

**Comment by jcb91** [comment]
So, the problem here is that the server doesn't load extensions based on the existence of files, but has a config file that tells it what extensions to load. In your current version of that config file, it's asked to load `usability/my_toc/toc_test`, but, since you've deleted the file, it fails to load it. Unfortunately, the `nbextensions` server extension only knows about extensions that have a `yaml` descriptor file. This means that if you have deleted the yaml descriptor, or altered it so that it refers to a different extension path , you can no longer use the `nbextensions` page to disable it. You can fix this quite easily from a python prompt, I'll get back to you in a minute with a solution...

**Comment by cqcn1991** [comment]
@jcb91 exactly, I think I've altered somewhere, maybe in a yaml file. But just couldn't find it. (I don't know the files' location, so I don't know where to perform a full-text search).

**Comment by jcb91** [comment]
So, this has a happened to me on a number of occasions, where I've had an extension enabled, then renamed or moved it, such that its path changes, without disabling it at the old path first. This means the server still tries to load the old extension path, which, of course, no longer exists. You can alter the config so the server won't load it anymore with

```python
from notebook.services.config import ConfigManager
path_to_disable = 'usability/my_toc/toc_test'
cm = ConfigManager()
cm.update('notebook', {'load_extensions': {path_to_disable: True}})
```

**Comment by cqcn1991** [comment]
@jcb91 just tried it. It works. That's really impressive.

**Comment by jcb91** [comment]
@cqcn1991 glad to hear it worked for you. If you want to find the config file itself (it's also the one used for lots of nbextensions' config settings), you can use

```python
from notebook.services.config import ConfigManager
cm = ConfigManager()
print(cm.file_name('notebook'))
```

which for me (on OSX) gives `/Users/josh/.jupyter/nbconfig/notebook.json`

**Comment by juhasch** [comment]
Can we close this ?

**Comment by cqcn1991** [comment]
@juhasch done.

**Comment by ruxi** [comment]
I tried to install NBextension via the pip method (didn't work, /nbextension resulted in 404 error) and then by git clone + setup.py (which did work). Now there are some duplicate menus in /nbextension. 

![image](https://cloud.githubusercontent.com/assets/6733446/13687053/bbe999d2-e6de-11e5-9c02-34251d8c57b8.png)

Any suggestions on how to fix? Or uninstall. 

Using anaconda3 on linux mint 17.3
