### ISSUE TITLE
Collapsible headings conflicts with display of docstring (Shift + Tab)

### ISSUE THREAD

**Issue by wielandbrendel** [ipython-contrib/IPython-notebook-extensions#509]
The notebook extensions and the GUI are great! What I noticed today is that the extension "collapsible headings" leads to weird behaviour with Shift+Tab (dropdown with docstring of function): it does not display, or only displays at the head of the notebook.

**Comment by jcb91** [comment]
Interesting! I wasn't aware that feature existed, it seems like it could be very useful. I can reproduce this behaviour on my notebook, disabling the extension allows the dropdown to show up again. I can't think of an obvious reason why this would happen, so I'll have a think/investigate. Thanks for the report @wielandbrendel

**Comment by wielandbrendel** [comment]
Dear jcb91, thanks for investigating! Indeed Shift+Tab is super useful. Which is why, sadly, I have to turn off the collapsible headings for now. Could the error have something to do with how Shift + Tab is computing where to put the dropdown (should be exactly located at the line)? Maybe the extension screws up this calculation?

**Comment by jcb91** [comment]
@wielandbrendel, yes it's exactly this. It appears that it's as a result of the css rule setting cells' position to relative, such that the code which calculates the tooltip's position is somehow coming up with the wrong answer. The position relative rule is in place for the mathematica-style brackets only, so if you're not using those, you could potentially comment out [nbextensions/usability/collapsible_headings/main.css#L58](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/1ccd6eefb991fb9f38dc2076a99e3417c7f416d3/nbextensions/usability/collapsible_headings/main.css#L58) as a temporary fix until I can think of something better...

**Comment by jcb91** [comment]
I've got a fix (see jcb91@486a82440ca722ef77d9a62df684d872ef4f8ed3) by patching the [tooltip method _show](https://github.com/jupyter/notebook/blob/216793eb2ab9efdbe80035a2762401fa5c1835b9/notebook/static/notebook/js/tooltip.js#L260) to essentially temporarily remove the css rule while the tooltip position is calculated, then reinstate it afterwards. For me, this happens quick enough that I don't even see the bracket move. It's not ideal, especially since the `_show` method is not part of the public API (leading underscore), so could change and break this fix at any time. However, the `tooltip.Tooltip` structure is such that I couldn't think of a better way to do it, and in any case, the patch doesn't actually affect how `_show` works, or even rely on its existence, so it should fail relatively gracefully. @wielandbrendel, if you could let me know whether this works ok for you, I can submit a PR for it.

**Comment by wielandbrendel** [comment]
Wow, that was superfast! I just tried it but I am not sure the fix works: I replaced the main.js in the jupyter data-folder (which in my case was /root/.local/share/jupyter/nbextensions/usability/collapsible_headings) with your version, and then turned on the extension in my jupyter kernel. No change, but maybe it did not catch the new main.js. I can try tomorrow by building my Docker container against your fork and starting a fresh kernel.

**Comment by jcb91** [comment]
Well, that (replacing the main.js file with the one from the correct branch), then reloading the page, should be enough, since as with most nbexrensions, this one is pure client-side JavaScript with no modification going on - the kernel isn't involved at all. Are you sure you've got the correct file? It seems from the path that you give that it'd only work if your notebook server is running as user `root`, which seems a little unusual (although perhaps not for a docker setup, I'm not sure)

**Comment by jcb91** [comment]
The other possibility is that I didn't specify correctly that you need to checkout the `usability/collapsible_headings` branch of my fork, not the default(`master`)

**Comment by wielandbrendel** [comment]
I built a new container against your branch and it seems to work fine! Thanks for the (very) quick fix!

**Comment by jcb91** [comment]
Ace, good to hear. You're welcome, I've been making various updates to this extension over the last few days, so it was fortuitously fresh in my mind :smile:
