### ISSUE TITLE
Installing latest version causes issues with numpy

### ISSUE THREAD

**Issue by AlecAivazis** [ipython-contrib/IPython-notebook-extensions#512]
I just installed the latest version by executing `./setup.py install` and now i get some errors whenever I try to import a package that depends on numpy. For example, when I try to import [pandas](https://github.com/pydata/pandas) I get:

```
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas/src/numpy.pxd", line 157, in init pandas.hashtable (pandas/hashtable.c:38262)
ValueError: numpy.dtype has the wrong size, try recompiling
```

I was able to get around this by installing an older commit. Specifically, [d23a7d](https://github.com/ipython-contrib/IPython-notebook-extensions/commit/d23a7d9443623a0f1eb01ca1fc7cf0ae113238d5).

**Comment by jcb91** [comment]
Wow, bizarre. So, this error seems to occur when `pandas` is built with a newer version of `numpy` than the one you're using (see, e.g. [this SO comment](http://stackoverflow.com/questions/17709641#comment25821367_17709641)).
So, presumably, this is something to do with nbextensions' dependency on `IPython` (which depends on `numpy`).

However, nothing in the dependencies has changed between d23a7d9443623a0f1eb01ca1fc7cf0ae113238d5 and the current head (724cb34a7012cc50cb9a77c1f1e1640f6c39b845).

So, the obvious place to look seems to be the `setup.py` script. My first thought is that this could be caused by the change in shebang at https://github.com/ipython-contrib/IPython-notebook-extensions/commit/2730ed3e936a5a849c2c2bb76ba2343b3553e1f1#diff-2eeaed663bd0d25b7e608891384b7298L1
The traceback indicates that you're using python 2.7, so I guess it's possible (?) that that's causing problems in a way it didn't before. Since `nbextensions` isn't actually a proper python package, it gets installed to `jupyter` directories, which may well be the same for both python 2 and 3 (?).

Could you give this a try, maybe?

**Comment by janschulz** [comment]
Just a shot in the dark: do you use conda? They had quite a few hiccups recently with installing mkl enabled libs and so on..

**Comment by AlecAivazis** [comment]
Sorry it took me so long to get back to you. Unfortunately, I'm not using conda

**Comment by juhasch** [comment]
Unlikely a nbextensions issue, especially after moving the server extension to the new repo.
Please reopen, if this still exists.
