### ISSUE TITLE
Is it possible to use scss for css writing?

### ISSUE THREAD

**Issue by cqcn1991** [ipython-contrib/IPython-notebook-extensions#531]
SCSS is easier to write, and the code looks much cleaner. Is it possible to use .scss rather than .css for a certain plugin?

**Comment by jcb91** [comment]
Well, you can write in whatever dialect you like (scss, less, etc), but we can't really ship the machinery to compile things.

The jupyter/notebook team store only the less in the repo, then generate css by compiling it using node in dev versions, and shipping the compiled (minus the less) css in the `pip` distributions (which don't require node). Since we currently don't have a separate pip version, this repo as it is now needs to contain everything required for someone to run it without dependencies ships only the bare minimum needed to run things. Since we can't (don't want to) rely on users having a dependency installed to compile things, if you want to use something like scss or less that needs compiling, I'd suggest you include both the source (scss) and derived (css) files for now.

Does that make sense?

**Comment by cqcn1991** [comment]
Then what would be a workflow with this?
I mean, I should convert the scss to css every time I changed the code when I'm developing. Is there any way to automate this?

**Comment by jcb91** [comment]
You might try using browser dev tools, like https://developer.chrome.com/devtools/docs/css-preprocessors

**Comment by juhasch** [comment]
I agree with @jcb91, let's not add another dependency here. There currently is only very little CSS in this repo.
