### ISSUE TITLE
ExecuteTime reports 6h 59m 57-59s for Julia and R kernels

### ISSUE THREAD

**Issue by joshjob42** [ipython-contrib/IPython-notebook-extensions#549]
It works fine in Python2, Python3, Octave, Cling/C++, and Bash (all the others I have installed). Is there any obvious reason why a kernel could be reporting times that are so wrong? If so, I can go submit issues with the respective kernels, but as of right now I'm not sure where to look.

**Comment by joshjob42** [comment]
For clarity, I mean that every time I run a kernel, it reports a time of 6h 59m and 57, 58, or 59s, pretty much at random.

**Comment by jcb91** [comment]
Hi there. That is an odd behaviour. The one thing that springs to mind is that perhaps one is being reported as a local time, and another as UTC - are you perhaps on a time zone 7 hours out from UTC? Are the execution times (as in, the times at which the executions were started) correct? If it _is_ a timezone issue, then that may be either a fault with the kernel, or with the nbextension, if it's just parsing the string incorrectly. I'll give this a go on my R kernel and see what the headers look like to try to gain some insight...

**Comment by jcb91** [comment]
So, it seems that neither the Julia nor the R kernel add the `msg.metadata.started` key to their `execute_reply` kernel messages, which means that the extension must rely on the javascript-generated start time. This will, of course, lead to slightly less accurate timings than if the kernel did the timing, but shouldn't lead to 7-hour errors. It would be nice if the kernels added the `started`key in future.

The 7-hour difference is, I suspect, caused by the fact that the kernels seem to report times in ISO8601 strings _without a timezone specified_, while the momentjs call which the extension uses formats them _with_ a UTC offset, so the UTC offset gets mixed in there. Unfortunately, as I'm currently in UTC, aI can't diagnose this directly, and so far I've been unable to discover how either the Julia or R kernels get the message `header.date` key set (it appears nowhere in their source, but is nonetheless set), so I'm currently in the dark about what formats to expect for it...

**Comment by joshjob42** [comment]
Hi, thank you for getting back to me! I actually am in UTC+7 (live in LA), so that seems likely to be the origin of the issue. The execution times are reported correctly in my time zone. When I switched the timezone on my Mac to UTC, both the execution times and run times were reported accurately. So it's definitely an issue with the time zone. In fact, when I changed it and reloaded the page, the old times were displayed correctly instead of with the original 7h runtime.

`message.metadata.started` is just the start time of the job execution as reported by the kernel? or is it the entire runtime?

**Comment by jcb91** [comment]
You're welcome :smile_cat: I really should have thought of just changing the timezone of my machine :dizzy_face: Good spot. The fact that the calculated execution times change when reloading the page also points to it being a problem with how momentjs is parsing dates without specified timezones, since 

So, the `message.metadata.started` is just the start time of the execution request, as reported by the kernel. You can see it it gets added in [ipykernel/kernelbase.py#L349-L356](https://github.com/ipython/ipykernel/blob/7e9b6862c5ffa9d6fb310da5840b4140adfdd06e/ipykernel/kernelbase.py#L349-L356)  for the ipython kernel. I'm not sure where `message.header.date` is added, I'm starting to wonder whether it's done automatically by zmq. I also haven't found anywhere any discussion on what date formats/timezones kernels should be using. I sort of think that they should specify the timezone just for reduced ambiguity, but python's `datetime` doesn't seem to do this by default...

**Comment by jcb91** [comment]
Thinking about this a little more, it seems that there are two problems, neither of which can be solved exclusively by the nbextension. However, perhaps it's possible to improve the current handling. As I see it:

1. The nbextension can't rely on the presence of the `message.metadata.started` value. It would be nice to add the key to kernels, but since it is not part of the [messaging spec](http://jupyter-client.readthedocs.org/en/latest/messaging.html), the nbextension can't rely on its presence.
2. 1. means that the nbextension must be able to calculate differences between server-provided `message.header.date` values, and javascript-provided start dates. This is what seems to be causing your 7-hour offset.
3. 2. is a problem, because all current kernel implementations seem to implement the `message.header.date` without a specified timezone, and thus this will cause problems whenever the server and client are in different timezones, however smart the nbextension javascript might be. I think it'd be worth adding PRs to jupyter_client (where I currently think this seems to be defined, either in [jupyter_client/adapter.py#L387-L388](https://github.com/jupyter/jupyter_client/blob/d82793dbdfb8589690dbdb96509c2814cadd444a/jupyter_client/adapter.py#L387-L388) or in [jupyter_client/jsonutil.py#L75-L80](https://github.com/jupyter/jupyter_client/blob/e4c5092c839ccc0690a3ba00d84607a353b31f57/jupyter_client/jsonutil.py#L75-L80), I'm not sure which is relevant) to get a timezone added.
4. I'm still not quite sure why this is causing a problem that you actually see, since [momentjs defaults](http://momentjs.com/docs/#/parsing/utc/) to interpreting strings as being in local timezone if none is specified, and, assuming that your server and client both use the same, correct, timezone, this should mean the comparison works ok. For example, when I change my machine's timezone to PST, comparisons of times recorded with the old timezone active break (since the server value is recorded in notebook metadata without timezone), but on re-executing the cell, they end up ok again - sort of the opposite of what you've described with your switch to UTC.

**Comment by joshjob42** [comment]
Aha! I found the problem! Well, it doesn't solve everything that may be wrong with the Jupyter ecosystem's time conventions, but it fixes my problem, haha. I use a docker container to run my dev/operating environment inlcuding Jupyter, and the container's timezone was set to UTC as I hadn't thought to change it. That's why my server and client were seeing different timezones and I was getting the opposite of what you see.

**Comment by jcb91** [comment]
Aha! So your client and server were (effectively) in different timezones. That makes sense then :+1: So, with that figured out, I don't think there's anything else that the nbextension can really do - the rest of the timestamp fixing belongs in jupyter and the various kernel projects...
