### ISSUE TITLE
slidemode is not listed in nbextensions

### ISSUE THREAD

**Issue by par2** [ipython-contrib/IPython-notebook-extensions#565]
I just installed nbextensions from the 4.x branch.  I'd like to use `slidemode`, but the options seems to be missing from the list.

![2016-04-03 01_17_26-notebook extension configuration](https://cloud.githubusercontent.com/assets/15694632/14230901/8e2d2b58-f93a-11e5-9cba-08940bd6f623.png)

Is there a reason why it is not listed?

**Comment by jcb91** [comment]
Hi there. So, it doesn't show up in the config page because it doesn't have a yaml descriptor file. Quite why it doesn't have a yaml descriptor I'm not completely sure, but it usually indicates that an extension hasn't been updated for some time. This seems to be the case for slidemode, judging by the note 

> This folder contains the legacy slidemode

in [the readme](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/nbextensions/slidemode/slidemode/README.md), and the fact that the extension definition doesn't return the now-required function `load_ipython_extension` (see [nbextensions/slidemode/slidemode/main.js#L340](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/nbextensions/slidemode/slidemode/main.js#L340).

I'm not really familiar with what slidemode is supposed to do - could you enlighten me a little? In the absence of further info, I wonder whether https://github.com/damianavila/RISE might be useful?

**Comment by par2** [comment]
Thanks for the response.  The [original slidemode](https://github.com/fperez/nb-slideshow-template) was the "live" presentation mode for ipython notebooks.  It existed as a js button that integrated with the native "View > Cell Toolbar > Slideshow" option for notebook cells.  Triggering slidemode displayed cells as slides that could be edited in realtime - a handy feature for lectures and coding demos.

I recall Damian was developing the "static" presentation version in parallel with slidemode i.e. [IPython-Reveal.js](https://www.youtube.com/watch?v=rBS6hmiK-H8).  It appears he may have attempted to [integrate the slidemode features](https://www.youtube.com/watch?v=Pc-1FS0l2vg) into his static version.  I did not realize his progress with [RISE](https://www.youtube.com/watch?v=sZBKruEh0jI), which appears to be "live" iteration of the former, so thank you for enlightening me about it.  

This new RISE appears to be a replacement for slidemode, combining the best slidemode and reveal.js.  Damian appears to be working at creating a [pip installable](https://github.com/damianavila/RISE/issues/187) package.  I suppose that answers my question.  Perhaps you may wish to integrate RISE as a supported nbextension in the future.  Thank you.

**Comment by par2** [comment]
An update to this thread, nbpresent is the next iteration of RISE https://github.com/Anaconda-Platform/nbpresent. Check it out.
