### ISSUE TITLE
ENC: Import/Export nbextension settings

### ISSUE THREAD

**Issue by par2** [ipython-contrib/IPython-notebook-extensions#566]
I'm setting up nbextensions on a second computer.  It would be great to simply import my current settings from computer one.  I imagine the settings are saved in yamls, but I am unfamiliar with the details. Can an import/export option be added to the nbextensions menu?

**Comment by jcb91** [comment]
The config for most nbextensions, along with their enabled/disabled status, is stored via the jupyter notebook's config API, in the appropriate section (which is `notebook` for almost all of them, though the javascript for `nbextensions.py` stores a single value in the `common` section, and the `tree-filter` extension's enable status is stored in the `tree` section). As a result, the config for nbextensions, either form this repo or others, isn't readily separable from anything else in the config, but I guess if you're trying to duplicate your original setup, that isn't too much of a  worry.

The config files are json files stored in jupyter's config directory, which you can find using

```bash
jupyter --config-dir
```

Or, if you'd like a list of the ones available and (potentially) relevant to nbextensions, you can use the following python snippet form the jupyter server machine:

```python
import os.path
from notebook.services.config import ConfigManager
cm = ConfigManager()
for section in ('edit', 'tree', 'notebook', 'common'):
    conf_path = cm.file_name(section)
    if os.path.exists(conf_path):
        print(conf_path)
```

As for an import/export option on the nbextensions menu - I guess you mean something that'd let you download the existing config as json, or upload a new one? I guess that'd be possible, certainly, but whether it would make sense to put it in the nbextensions config menu, I'm not sure, since it can potentially affect other things?

**Comment by jcb91** [comment]
Also, for anyone interested, the yaml files contain information for the config extension (that's the one in this repo that provides the nbextension configuration/enabling page at `/nbextensions`) to allow it to know the default values for, and update the correct keys in, the json config files through the jupyter config service javascript. The yaml files themselves never get altered.

**Comment by par2** [comment]
Thanks for the info.  Locating the config file should work for future endeavors.

**Comment by par2** [comment]
An update to this thread, nbpresent is the next iteration of RISE https://github.com/Anaconda-Platform/nbpresent.  Check  it out.

**Comment by jcb91** [comment]
Thanks for the pointer, but I think you may have meant this for another thread?

**Comment by jfbercher** [comment]
@par2 This link is very interesting. Thanks for the information.

**Comment by par2** [comment]
Correct jc91.  I removed the comment and reposted elsewhere. Thank you.

**Comment by jcb91** [comment]
Thanks @par2. For anyone wondering, it's now at https://github.com/ipython-contrib/IPython-notebook-extensions/issues/565#issuecomment-217563820
