### ISSUE TITLE
    ImportError: No module named 'nbextensions'

### ISSUE THREAD

**Issue by cptdime** [ipython-contrib/IPython-notebook-extensions#579]
I have been trying and trying for hours to get nbextensions installed.  I started from a clean home directory:

rm -rf ~/.local
rm -rf ~/.cache
rm -rf ~/.jupyter
rm -rf ~/.ipython

I've tried Anaconda 2 and 3, versions 4, 2.4.0 and 2.4.1 on each.  I've tried the pip install and I've tried pulling the git repo and doing setup.py install.  I get the same result everytime: 

jupyter notebook --no-browser
[W 17:53:26.900 NotebookApp] Error loading server extension nbextensions
    Traceback (most recent call last):
      File "/p/home/ggeorge/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 991, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/p/home/ggeorge/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
    ImportError: No module named 'nbextensions'

Any ideas?

**Comment by jcb91** [comment]
Hi! Sorry to hear you're having trouble. This seems a similar issue in form to #576, although whether the actual cause is the same isn't clear.

I'm not sure what's gone wrong with the installation attempts you've tried thus far, but I can try to help you fix it so that the extension works, even if the install doesn't manage it alone. I take it you saw no error messages while running `pip install` / `setup.py`?

So, the error that you quote from the server log 

> `ImportError: No module named 'nbextensions'` 

indicates that:

* the `jupyter_notebook_config.json` config file was correctly modified by the `configure_nbextensions.py` script (run by the `setup.py` script, which is run by pip) to request the loading of the `nbextensions` jupyter server extension
* either the `jupyter_notebook_config.py` file was not correctly modified to edit `sys.path`, or the `nbextensions.py` file wasn't copied to the correct location.


What should happen in the install process is:

1. in `install.py` (also run by `setup.py`), the server extension file (`nbextensions.py`) is copied into a directory `extensions` inside your jupyter data directory (which you can find using `jupyter --data-dir`). Your first check should be to see what exists there.
2. in `configure_nbextensions.py`, a python jupyter config file is created/modified. In this config file, `sys.path` is extended to include the folder mentioned above. Your second set of things to check should be 
  * whether this config file exists
  * whether it has lines modifying `sys.path`
  * whether any additions to `sys.path` correspond to the directory mentioned in 1.

You can find the relevant `jupyter_notebook_config.py` config file using the following python snippet:

```python
import os
from jupyter_core.paths import jupyter_config_path

for p in jupyter_config_path():
    conf_path = os.path.join(p, 'jupyter_notebook_config.py')
    if os.path.exists(conf_path):
        print(conf_path)
```

And you can find the directory which should be appended to `sys.path`, and in which the extension should exist, using this snippet:

```python
import os
from jupyter_core.paths import jupyter_data_dir
ext_dir = os.path.join(jupyter_data_dir(), 'extensions')
```

Let me know how you get on!

**Comment by pybokeh** [comment]
I have similar error after upgrading to notebook version 4.2:
    
    [W 09:06:34.521 NotebookApp] server_extensions is deprecated, use nbserver_extensions
    [W 09:06:34.744 NotebookApp] Error loading server extension nbextensions
        Traceback (most recent call last):
          File "/home/pybokeh/envs/jupyter/lib/python3.5/site-packages/notebook/notebookapp.py", line 1042, in init_server_extensions
            mod = importlib.import_module(modulename)
        File "/opt/python3.5.1/lib/python3.5/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 986, in _gcd_import
        File "<frozen importlib._bootstrap>", line 969, in _find_and_load
        File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
      ImportError: No module named 'nbextensions'
    

I installed jupyter notebook via:
    
    pip install -U jupyter
    

Then installed the notebook extensions via:
    
    pip install -U https://github.com/ipython-contrib/IPython-notebook-extensions/archive/master.zip --user
    

Regarding @jcb91 comments concerning location of nbextensions.py.  I do have the "extensions" directory but it does not contain the nbextensions.py file.  However, I found a copy located here in my virtual environment's directory:
/home/pybokeh/envs/jupyter/lib/python3.5/site-packages/notebook/nbextensions.py

I also can not find the configure_nbextensions.py file.  I even looked in my virtual environment folder:
/home/pybokeh/envs/jupyter/lib/python3.5/site-packages/notebook/
This folder does contains notebookapp.py, serverextensions.py, and nbextensions.py, but not configure_nbextension.py.

When I ran this:
    
    import os
    from jupyter_core.paths import jupyter_data_dir
    ext_dir = os.path.join(jupyter_data_dir(), 'extensions')
    
I did not get any output all.

So based on @jcb91 's comments, it appears perhaps something went wrong during the setup.py process during pip installation??

Otherwise, my nb extensions are stil working and my juypter notebook appears to be working ok.  I just get that error when launching the notebook server.

**Comment by jcb91** [comment]
Apologies for the confusion here, there's a good deal of different things with similar names going on.

@pybokeh yes, it seems that something in the `setup.py` installation hasn't worked as expected. I suspect this may be related to the use of virtual environments, but perhaps not. Comments below...

The nbextensions file you mention:
> However, I found a copy located here in my virtual environment's directory:
> `/home/pybokeh/envs/jupyter/lib/python3.5/site-packages/notebook/nbextensions.py`

is actually a different file, part of the jupyter notebook package, rather than the server extension from this repo, although they both have the same name. This is a bit confusing, so I think in future we'd be better renaming the server extension to something less ambiguous.

> I also can not find the `configure_nbextensions.py` file

That's ok, and expected. The `configure_nbextensions.py` script is part of this repository, but isn't intended to be installed (it's only used by the `setup.py` script which does the installation, nothing else) so you wouldn't expect to find it in your python environment.

> I did not get any output all.

Apologies, my fault, when running from a regualr (non-ipython) prompt, you need a print statement there, so it should have read

```python
import os
from jupyter_core.paths import jupyter_data_dir
ext_dir = os.path.join(jupyter_data_dir(), 'extensions')
print(ext_dir)
```

If you're confident you've found the correct `extensions` directory, you can grab the (current, 7153db813) version of the server extension from 
https://github.com/ipython-contrib/IPython-notebook-extensions/blob/7153db8138081e3a2b61e79e6b174db87f042279/extensions/nbextensions.py to save it manually.

However, you may still need to check whether the config file extending your path has been put in the right place (see snippet in my previous reply)...

**Comment by juhasch** [comment]
I just tried this in a Linux Mint Virtualbox:
```
pip install -U https://github.com/ipython-contrib/IPython-notebook-extensions/archive/master.zip --user
```
and it looks like it does not call `install.py` and `configure_nbextensions.py` at all.
No wonder that the files cannot be found.

**Comment by juhasch** [comment]
Well, `install.py` is not doing anything, as `main()` never get's called from `setup.py`.

**Comment by pybokeh** [comment]
@jcb91 I copied the nbextensions.py from the link you provided and saved it into my "extensions" folder, now no more error!  But I do get warning message:
    
    [W 10:44:19.717 NotebookApp] server_extensions is deprecated, use nbserver_extensions
   
Which is expected I guess.  Thanks!

**Comment by jfbercher** [comment]
`install;py` is imported in `setup.py` when pip is called with install in arguments eg `pip install etc`, then its contents interpreted. Since the nbextensions collection is installed, it seems that installation is correctly launched. It is possible that the destination for nbextension.py is not correctly detected in case of a (his?) virtual env.

**Comment by juhasch** [comment]
@jfbercher: `install.py` is imported in `setup.py`, but the actual file copying is called from the `main()` function of `install.py` which never gets called.

**Comment by jcb91** [comment]
Argh! apologies all, this is my fault, from #569. I'll push a fix imminently

**Comment by juhasch** [comment]
@jcb91 Thanks :-)

**Comment by jcb91** [comment]
Ok, I've fixed `setup.py` to actually call the functions in `install.py`, so it should now hopefully all work ok.

This is yet another instance of me inadvertently breaking something while trying to fix something else, so another upvote for CI testing, I think! I've now got a working version which tests installation across notebook versions 4.0 through 4.x in my trav branch, which has already caught a couple of things I'd missed in my own branches...

**Comment by jcb91** [comment]
@pybokeh yes, this is expected, we haven't yet updated the `configure_extensions.py` script to use the new config key. I'll fix this shortly.

**Comment by jfbercher** [comment]
Thanks @jcb91 . I didn't noticed the new main().

**Comment by jfbercher** [comment]
In passing. It was certainly a nice idea to keep track of installed files. We may also try store the install date and only overwrite unmodified ones (at least for css -- this would allow users to customize these files), or ask for confirmation?

**Comment by jcb91** [comment]
@jfbercher we could, and that would be nice, but in light of the updates in notebook 4.2 which include more robust installation mechanisms for nbextensions (includes checking modification times), I think we ought to move to the standardized, jupyter-provided installation mechanism, to reduce the potential for confusing everybody :stuck_out_tongue_closed_eyes:.

I'm not sure how best to handle customizing css or uninstalling old extensions using the new jupyter mechanisms though...

**Comment by jcb91** [comment]
config key updated in #581

**Comment by cptdime** [comment]
Hi all, 

I can confirm that the issue is fixed for me now.  I did pip install --upgrade and I can now see the extensions.  

Cheers.
