### ISSUE TITLE
Config option 'nbserver_extensions' not recognized by 'NotebookApp'.

### ISSUE THREAD

**Issue by waio1990** [ipython-contrib/IPython-notebook-extensions#606]
Had a nice install with conda 4.0 until I ran a notebook and got this in the initialisation:

`[W 17:00:15.380 NotebookApp] Config option `nbserver_extensions` not recognized by `NotebookApp`.  Did you mean one of: `reraise_server_extension_failures, server_extensions`?`

Not sure what this means, and rather noob with jupyer.

Any help is appreciated

**Comment by jcb91** [comment]
Well, this seems to be related to the change from Jupyter 4.2, when the config key used to determine which server extensions to load was changed from a list called `server_extensions`, to a dict called `nbserver_extensions`.

My guess is that you're using jupyter < 4.2, and either you're using an IPython 3.x setup (seems unlikely?), or somehow our version detection isn't working correctly.

Could you please post the lines you use to launch the jupyter server, along with the output of 

```bash
jupyter notebook --version
```

The current `configure_nbextensions.py` script attempts (in [configure_nbextensions.py#L158-L161](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/a81e759c75ee9f6510009e792b1f7f6553749d7f/configure_nbextensions.py#L158-L161)) to detect support based on the value of `notebook.version_info`, which is perhaps not the right way to go about it. It would be more robust to check for the existence or otherwise of the `nbserver_extensions` attribute on the `NotebookApp` class, I suppose.

**Comment by waio1990** [comment]
I have Jupyter 4.1.0, and I simply go with 
`jupyter notebook`

to start, will try after an update

**Comment by jcb91** [comment]
hi, sorry, only just noticed you edit (I guess github doesn't notify for edits?)

Ok, well, the install _should_ have worked for jupyter 4.1 but it seems that for some reason the `configure_nbextensions.py` script got the version wrong. I'm still not sure why that happened.

Now, with your jupyter 4.2 install, it seems that the config file hasn't been written correctly: the python path is extended by a python config file written in [configure_nbextensions.py#L38-L59](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/50ae35e4b1c5bd730a5eb470326e3f0db2c62149/configure_nbextensions.py#L38-L59) to include the jupyter data directory, into which the server extension is copied by the `install.py` script. It seems that for some reason that hasn't happened correctly for you.

What do you get from (python):

```python
import os
import glob

from jupyter_core.paths import jupyter_config_dir, jupyter_data_dir

pats = {
    'config': os.path.join(jupyter_config_dir(), '*'),
    'extensions': os.path.join(jupyter_data_dir(), 'extensions', '*'),
}
for name, pat in pats.items():
    print('{}:\n  {}'.format(name, '\n  '.join(glob.glob(pat))))
```

**Comment by waio1990** [comment]
No need to apologise lol, you're helping me.

here is the output of the script:

`config:
  /Users/waio/.jupyter/jupyter_nbconvert_config.json
  /Users/waio/.jupyter/jupyter_nbconvert_config.json.bak
  /Users/waio/.jupyter/jupyter_nbconvert_config.py
  /Users/waio/.jupyter/jupyter_nbconvert_config.py.bak
  /Users/waio/.jupyter/jupyter_notebook_config.json
  /Users/waio/.jupyter/jupyter_notebook_config.json.bak
  /Users/waio/.jupyter/jupyter_notebook_config.py
  /Users/waio/.jupyter/jupyter_notebook_config.py.bak
  /Users/waio/.jupyter/migrated
  /Users/waio/.jupyter/nbconfig
extensions:
  /Users/waio/Library/Jupyter/extensions/highlight_html_cfg.py
  /Users/waio/Library/Jupyter/extensions/highlight_latex_cfg.py
  /Users/waio/Library/Jupyter/extensions/nbextensions.py
  /Users/waio/Library/Jupyter/extensions/post_embedhtml.py
  /Users/waio/Library/Jupyter/extensions/pp_highlighter.py
  /Users/waio/Library/Jupyter/extensions/pre_codefolding.py
  /Users/waio/Library/Jupyter/extensions/pre_collapsible_headings.py
  /Users/waio/Library/Jupyter/extensions/pre_pymarkdown.py
  /Users/waio/Library/Jupyter/extensions/pre_svg2pdf.py
  /Users/waio/Library/Jupyter/extensions/strip_output_prompt.py`

**Comment by waio1990** [comment]
Here is my build output for the package:
`Installed /Users/waio/anaconda/envs/_build/lib/python3.5/site-packages/Python_contrib_nbextensions-alpha-py3.5.egg
Processing dependencies for Python-contrib-nbextensions===alpha
Searching for traitlets==4.2.1
Best match: traitlets 4.2.1
Adding traitlets 4.2.1 to easy-install.pth file

Using /Users/waio/anaconda/envs/_build/lib/python3.5/site-packages
Searching for tornado==4.3
Best match: tornado 4.3
Adding tornado 4.3 to easy-install.pth file

Using /Users/waio/anaconda/envs/_build/lib/python3.5/site-packages
Searching for PyYAML==3.11
Best match: PyYAML 3.11
Adding PyYAML 3.11 to easy-install.pth file

Using /Users/waio/anaconda/envs/_build/lib/python3.5/site-packages
Searching for psutil==4.2.0
Best match: psutil 4.2.0
Adding psutil 4.2.0 to easy-install.pth file

Using /Users/waio/anaconda/envs/_build/lib/python3.5/site-packages
Searching for notebook==4.2.0
Best match: notebook 4.2.0
Adding notebook 4.2.0 to easy-install.pth file

Using /Users/waio/anaconda/envs/_build/lib/python3.5/site-packages
Searching for nbconvert==4.2.0
Best match: nbconvert 4.2.0
Adding nbconvert 4.2.0 to easy-install.pth file

Using /Users/waio/anaconda/envs/_build/lib/python3.5/site-packages
Searching for jupyter-core==4.1.0
Best match: jupyter-core 4.1.0
Adding jupyter-core 4.1.0 to easy-install.pth file`

And my Path file:

`
# Setting PATH for Python 3.4
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
export PATH

# Added by Canopy installer on 2016-05-13
# VIRTUAL_ENV_DISABLE_PROMPT can be set to '' to make the bash prompt show that Canopy is active, otherwise 1
alias activate_canopy="source '/Users/waio/Library/Enthought/Canopy_64bit/User/bin/activate'"
# VIRTUAL_ENV_DISABLE_PROMPT=1 source '/Users/waio/Library/Enthought/Canopy_64bit/User/bin/activate'

# added by Anaconda3 4.0.0 installer
export PATH="/Users/waio/anaconda/bin:$PATH"

#Locale fixing
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8`

**Comment by jcb91** [comment]
Ok, so all the extension files seem to have been copied into the correct location. What's the contents of the file `/Users/waio/.jupyter/jupyter_notebook_config.py`? It should contain a couple of lines like

```python
import sys
sys.path.append('/Users/waio/Library/Jupyter/extensions/')
```

but it seems from your error 

> ImportError: No module named 'nbextensions'

that perhaps those lines are missing, since it was intended to import the file `/Users/waio/Library/Jupyter/extensions/nbextensions.py`...



(in other news, fwiw, I suspect that the origin of the original 

> `[W 17:00:15.380 NotebookApp] Config optionnbserver_extensionsnot recognized byNotebookApp. Did you mean one of:reraise_server_extension_failures, server_extensions?`

was the existence of two different notebook versions (4.1.0 and 4.2.0) in different virtualenvs, but that's a bit neither-here-nor-there now anyway).

**Comment by waio1990** [comment]
Finally it works!

The problem was the path you mentioned, I opened and saw:

`import sys
sys.path.append('/Users/waio/anaconda/envs/_build/share/jupyter/extensions')`
Added a second append with the correct location and now it works.

**Comment by jcb91** [comment]
😄 glad you got it working!

It seems like you ran into problems with the way conda installs things - I'm not familiar with it, but it appears maybe it `pip install`s into a staging environment (`/Users/waio/anaconda/envs/_build`), then moves things into another location afterwards,whcih would nobble our current install mechanism.

Another plus-vote for #577, I think 😜

**Comment by juhasch** [comment]
The server extension is now a separate package.
