### ISSUE TITLE
Python Markdown within an Equation 

### ISSUE THREAD

**Issue by Shaun1818** [ipython-contrib/IPython-notebook-extensions#608]
I want the to display code varibles within a markdown equation, like this
$$ w =\frac{a}{f} \cdot {{x}}$$
 however i get this error
![image](https://cloud.githubusercontent.com/assets/19259454/15389731/6971811e-1e0c-11e6-8f45-386a14240d4c.png)

**Comment by juhasch** [comment]
This does not work. The reason is the asynchronous operation of markdown cell rendering, math rendering, and code execution. So while the code `{{x}}` is being executed, the math rendering has already started. 
This could theoretically be solved by patching the notebook code itself, I tried to avoid this because then the extension gets highly version depdendent.

**Comment by juhasch** [comment]
Duplicate of #514
