### ISSUE TITLE
IPython Markdown not working when saving as HTML

### ISSUE THREAD

**Issue by Shaun1818** [ipython-contrib/IPython-notebook-extensions#610]
When i save a notebook as HTML which call a code variable inside a markdown, it does not show it correctly as shown in the figure below

![image](https://cloud.githubusercontent.com/assets/19259454/15500271/1dd51f6a-21fc-11e6-88b1-411ef0b75f9a.png)

**Comment by clayms** [comment]
Same thing happens when using [nbconvert](https://github.com/jupyter/nbconvert/issues/320) to pdf.

**Comment by jcb91** [comment]
@clayms if you run nbconvert with the debug flag, you should hopefully be able to see which preprocessors are being used - there should be a `pre_pymarkdown.PyMarkdownPreprocessor` preprocessor which does the variable substitution? It should be configured in one of the install scripts (see [configure_nbextensions.py#L142](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/configure_nbextensions.py#L142)), but it's possible that config gets confused by being set in other places, since the preprocessors are a list, so the whole list can get replaced ratehr than being appended to. 

@Shaun1818 apologies for the late reply. How are you saving as html? Using the `File > Download as... > HTML (.html)` menu item? Can you get debug-level logging, e.g. running the server with the `--debug` flag?

**Comment by clayms** [comment]
@Shaun1818, Thanks to @juhasch and reading instructions more thoroughly, downloaded  [`pre_pymarkdown.py` ](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/extensions/pre_pymarkdown.py) and put in my `PYTHONPATH` folder, which for me is the Anaconda folder. 

I think this issue can also be closed now, same as the referenced issue on [nbconvert](https://github.com/jupyter/nbconvert/issues/320) repo.

**Comment by jcb91** [comment]
@clayms ah, thanks, didn't notice it was a link to a specific issue! (https://github.com/jupyter/nbconvert/issues/320 in case anyone else is as lazy as me 😄)
