### ISSUE TITLE
 temporary cell floating on the bottom extension

### ISSUE THREAD

**Issue by lspvic** [ipython-contrib/IPython-notebook-extensions#612]
Is there a extension that floating a temporary cell on the bottom, so it's conviniecnt for debug, look at variable values, test expressions?
e.g. if we want to know the usage of the sorted method, we type sorted? to a new cell and run cell, after reading the usage, it is very likely that the cell will be deleted.
if there's a temporary floating cell, at any time, we type a expression, a variable and run.

**Comment by jcb91** [comment]
Something like the scratchpad extension?

**Comment by lspvic** [comment]
@jcb91 thanks！
I tried scratchpad, it is really what i want. But I found that I can't run the cell, the scatchpad cannot be selected. Do you know how to?

**Comment by jcb91** [comment]
Ah, I'm not really sure what you mean. What happens when you try to select
it? How did you try to run it? Toolbar buttons, ctrl-enter? I'm away from a
computer right now, but will give it a try when I return...

**Comment by lspvic** [comment]
@jcb91 ctrl-enter and toolbar buttons don't work. when i enter a command in the scatchpad cell and ctrl-enter it run the notebook cell not the command in scatchpad

**Comment by jcb91** [comment]
Right! Just looked at the code, and it seems that scratchpad registers a
different keyboard shortcut for execution than a regular cell, in order
(presumably) not to clobber any existing functionality. So, to execute the
scratchpad cell, you need to use shift-enter instead of ctrl-enter. Perhaps
it might be worth adding a button for execution as well, and maybe a note
in the readme. Worth mentioning scratchpad's author @minrk, too.

**Comment by jcb91** [comment]
It looks like this is fixed, so I'm going to go ahead and close, please reopen if not.
