### ISSUE TITLE
table_beautifier in html export?

### ISSUE THREAD

**Issue by Foucl** [ipython-contrib/IPython-notebook-extensions#637]
Is it necessary to write a post-processor so that tables are styled by table_beautifier when using nbconvert?

**Comment by janschulz** [comment]
yes, currently it's only a notebook frontend.

**Comment by jcb91** [comment]
We have a few extensions which would benefit from a pre/post-processor to insert javascript & css, perhaps we might consider a common machinery? Offhand I can think of

* table_beautifier
* collapsible_headings
* toc2 (which already has an exporter, I think, perhaps worth adapting?)

**Comment by Foucl** [comment]
If I wasn't a bit confused by how the concepts of 'templates' (used by toc2 and toc3 for example) and 'pre-/post-processors' (used e.g. by toc2 and code-folding; they seem to be regular jupyter extensions) relate to each other, I would offer help.

On a related note: It would never be possible to have the 'offical' github/nbviewer renderer apply such templates/processors, correct?

Should this issue stay open or should I close it? My initial question is answered.

**Comment by jcb91** [comment]
> If I wasn't a bit confused by how the concepts of 'templates' (used by toc2 and toc3 for example) and 'pre-/post-processors' (used e.g. by toc2 and code-folding; they seem to be regular jupyter extensions) relate to each other, I would offer help.

As I understand it, the export model is:

1. Pre-processor(s). A python class which operates on the notebook json document. Can be used to, e.g. remove output from cells based on metadata. Multiple preprocessors can be applied.
2. Exporter. Another python class, which takes the notebook json and turns it into html/latex/whatever according to the template. Template can be specified in the command, or get default from the exporter (the technique used in the `toc2.py` exporter to set the default template to be the `toc3.tpl`)
3. Template. a jinja2 template rendered using variables from the exporter (I think, this is the bit I'm least certain about).
4. Postprocessor. Another python class which operates on the output of the template-rendering process (so html/latex/markdown text, whatever). This is used, for example, in `highlighter` to do text replacements to replace tags inserted by a pre-processor. I think only a single postprocessor can be specified, although I can't right now think of an obvious reason why that should be the case.

> It would never be possible to have the 'offical' github/nbviewer renderer apply such templates/processors, correct?

I guess not, without getting them to adopt them officially. Unless their renderers honour executed  `%%javascript` cell-magics (which seems extremely unlikely, since the notebooks would be untrusted, and therefore run through the html sanitizer which would strip out css and javascript tags).

> Should this issue stay open or should I close it? My initial question is answered.

I guess we can close this, and reopen any new issue/PR as necessary for altering processors etc. I'll do that now.

**Comment by jfbercher** [comment]
>>If I wasn't a bit confused by how the concepts of 'templates' (used by toc2 and toc3 for example) and 'pre-/post-processors' (used e.g. by toc2 and code-folding; they seem to be regular jupyter extensions) relate to each other, I would offer help.
As I understand it, the export model is:

>1. Pre-processor(s). A python class which operates on the notebook json document. Can be used to, e.g. remove output from cells based on metadata. Multiple preprocessors can be applied.
2. Exporter. Another python class, which takes the notebook json and turns it into html/latex/whatever according to the template. Template can be specified in the command, or get default from the exporter (the technique used in the toc2.py exporter to set the default template to be the toc3.tpl)

Yes. Actually, I far as I understand myself, the exporter can only work if registered in the system which seems to require that the extension is installed as a "package". I have prepared the exporter but not yet transformed this extension into a separate package. The interest would be to have an export like `jupyter nbconvert FILE -to html_toc`

>3. Template. a jinja2 template rendered using variables from the exporter (I think, this is the bit I'm least certain about).

Do not need to rely on a exporter; many tests and conditions (using cells metadata for instance) can already be  embedded in it. 

>4. Postprocessor. Another python class which operates on the output of the template-rendering process (so html/latex/markdown text, whatever). This is used, for example, in highlighter to do text replacements to replace tags inserted by a pre-processor. I think only a single postprocessor can be specified, although I can't right now think of an obvious reason why that should be the case.

Yes. Unfortunately it seems that a single  postprocessor can be specified. This is a limitation for our repo where it would be interesting to have several postprocessors preconfigured.
